name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Debug secrets present
        run:  echo "AWS Key Present ${{ secrets.AWS_ACCESS_KEY_ID != '' }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
          AWS-SECRET-ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
          aws-region: us-east-1

      - name: Deploy with Serverless
        env:
          PLAID_CLIENT_ID: ${{ secrets.PLAID_CLIENT_ID }}
          PLAID_SECRET: ${{ secrets.PLAID_SECRET }}
        run: sls deploy